### ISSUE TITLE
Span-has data hangs

### ISSUE THREAD

**Issue by tylas13** [galak/span-hacs#5]
I pulled in @jeffkibuule build and got it working after the system failed to respond after a router reboot last week.  This fixed the issue, but after 2-8 hours the data hangs and get the following in the logs:

`Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172 
First occurred: 12:12:15 PM (4 occurrences) 
Last logged: 12:12:15 PM

Error unloading entry Span Panel nt-2142-c1aj0 for binary_sensor
Error unloading entry Span Panel nt-2142-c1aj0 for select
Error unloading entry Span Panel nt-2142-c1aj0 for sensor
Error unloading entry Span Panel nt-2142-c1aj0 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 496, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 173, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!`

**Comment by tylas13** [comment]
I have found a little more, when I reload the integration I get this error message:

```
"Logger: homeassistant
Source: custom_components/span_panel/select.py:57 
Integration: Span Panel ([documentation](https://github.com/galak/span-hacs), [issues](https://github.com/galak/span-hacs/issues)) 
First occurred: 8:31:58 PM (301 occurrences) 
Last logged: 9:23:47 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/span_panel/select.py", line 57, in current_option
    return PRIORITY_TO_HASS[priority]
KeyError: 'NON_ESSENTIAL'
```

So when I reload the integration I can't get anything to move, but when I restart Home Assistant I can get it to reconnect for a few hours.

**Comment by galak** [comment]
@tylas13 what firmware version are you on?

**Comment by tylas13** [comment]
I am on Span Panel (00200) by Span, Firmware: spanos2/r202223/04

Just tried rebooting again and it grabbed one set of data and now is frozen again.  I tried turning off my dryer breaker, but the service failed to turn off and on again.  

edit: I should say, from HA it failed. The panel, app, and internal website are working fine.

**Comment by galak** [comment]
What does a dump of `http://<SPAN_IP>/api/v1/circuits` get you?

**Comment by tylas13** [comment]
Thanks for looking into it galak:

`{"circuits":{"d79a18a4bd2a443aafa12316c345b2ac":{"id":"d79a18a4bd2a443aafa12316c345b2ac","name":"Range","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":503.1325378417969,"consumedEnergyWh":7809.218505859375,"energyAccumUpdateTimeS":1661222964,"tabs":[1,3],"priority":"NICE_TO_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"0690322665414e8587d41e9538315978":{"id":"0690322665414e8587d41e9538315978","name":"Dryer","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":593.5554351806641,"consumedEnergyWh":258758.8515625,"energyAccumUpdateTimeS":1661222964,"tabs":[5,7],"priority":"NON_ESSENTIAL","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"ed11f03ae74d4bd38a233ea87a43468b":{"id":"ed11f03ae74d4bd38a233ea87a43468b","name":"Bsmt dining,dishwasher, hood, disposal","relayState":"CLOSED","instantPowerW":-888.4403610229492,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":11.615446054493077,"consumedEnergyWh":535443.900390625,"energyAccumUpdateTimeS":1661222964,"tabs":[9,11],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"c6c5104b0ff44d8d87ed7410357fef70":{"id":"c6c5104b0ff44d8d87ed7410357fef70","name":"Kitchen fridge and dishwasher","relayState":"CLOSED","instantPowerW":-4.5853317975997925,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":91.7604990079999,"consumedEnergyWh":23822.051025390625,"energyAccumUpdateTimeS":1661222964,"tabs":[13,15],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"012f2a6af2f146d7bf6d4e170a7d23c7":{"id":"012f2a6af2f146d7bf6d4e170a7d23c7","name":"Rec room outside stove hood","relayState":"CLOSED","instantPowerW":-105.43989562988281,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":0.02816645119446548,"consumedEnergyWh":217224.6484375,"energyAccumUpdateTimeS":1661222964,"tabs":[17,19],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"3b930553fbf94795a7dc6c18c4da0a43":{"id":"3b930553fbf94795a7dc6c18c4da0a43","name":"Basement computer, bath, bed","relayState":"CLOSED","instantPowerW":-153.28946602344513,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":8055.598561286926,"consumedEnergyWh":251344.564453125,"energyAccumUpdateTimeS":1661222964,"tabs":[2,4],"priority":"MUST_HAVE","is_user_controllable":false,"is_sheddable":false,"is_never_backup":false},"8ff1f73967834614be3b98f23b6bc894":{"id":"8ff1f73967834614be3b98f23b6bc894","name":"Well","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":1435.13427734375,"consumedEnergyWh":73983.55859375,"energyAccumUpdateTimeS":1661222964,"tabs":[6,8],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"183c8d9ceade4f1691e9b0e4d5b3c906":{"id":"183c8d9ceade4f1691e9b0e4d5b3c906","name":"Pole Barn","relayState":"CLOSED","instantPowerW":-86.11837387084961,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":0.26490556448698044,"consumedEnergyWh":386973.546875,"energyAccumUpdateTimeS":1661222964,"tabs":[30,32],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"1fe30c0ecaa7403482d038190e940c8f":{"id":"1fe30c0ecaa7403482d038190e940c8f","name":"Furnace Fan","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":156.6168670654297,"consumedEnergyWh":2158.14794921875,"energyAccumUpdateTimeS":1661222964,"tabs":[26,28],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"44799bdc57314366a13e2118dfcf131f":{"id":"44799bdc57314366a13e2118dfcf131f","name":"Furnace Compressor","relayState":"CLOSED","instantPowerW":-13.152661800384521,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":0.01793723227456212,"consumedEnergyWh":144470.8671875,"energyAccumUpdateTimeS":1661222964,"tabs":[22,24],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"96e9456034124d938b88c33ced6304ee":{"id":"96e9456034124d938b88c33ced6304ee","name":"Basement range","relayState":"CLOSED","instantPowerW":-3.9234139919281006,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":497.0860023498535,"consumedEnergyWh":56678.259765625,"energyAccumUpdateTimeS":1661222964,"tabs":[18,20],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"dc2c54821aa148aeb24fd723838399b8":{"id":"dc2c54821aa148aeb24fd723838399b8","name":"Kitchen outlets","relayState":"CLOSED","instantPowerW":-7.948257923126221,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":2220.27685546875,"consumedEnergyWh":9796.6455078125,"energyAccumUpdateTimeS":1661222964,"tabs":[10],"priority":"NICE_TO_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"f57d781043e14ca6a03cec523286a834":{"id":"f57d781043e14ca6a03cec523286a834","name":"Kitchen outlets island","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":6.476463794708252,"consumedEnergyWh":20062.36328125,"energyAccumUpdateTimeS":1661222964,"tabs":[12],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"ba10253825c446788b09a0d883bdd701":{"id":"ba10253825c446788b09a0d883bdd701","name":"Basement kitchen and dining","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":16.880611419677734,"consumedEnergyWh":43614.9140625,"energyAccumUpdateTimeS":1661222964,"tabs":[14],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"58e92c145fe249d2931435424496ef1f":{"id":"58e92c145fe249d2931435424496ef1f","name":"Washer and Softener","relayState":"CLOSED","instantPowerW":-129.94659423828125,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":7.05820894241333,"consumedEnergyWh":167129.140625,"energyAccumUpdateTimeS":1661222964,"tabs":[16],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"6c125f348b41435fa80f93de45fabc21":{"id":"6c125f348b41435fa80f93de45fabc21","name":"Larryâ€™s Living Room/Garage","relayState":"CLOSED","instantPowerW":-347.9596862792969,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":0.0,"consumedEnergyWh":451486.46875,"energyAccumUpdateTimeS":1661222964,"tabs":[21],"priority":"NICE_TO_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"05f63ad9d182422294e711818cae4482":{"id":"05f63ad9d182422294e711818cae4482","name":"Upstiars deck light and plugs","relayState":"CLOSED","instantPowerW":-4.288037300109863,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":0.00016166208661161363,"consumedEnergyWh":10417.4111328125,"energyAccumUpdateTimeS":1661222964,"tabs":[23],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"77dde705fb3443b5a61abd8cfbf3112a":{"id":"77dde705fb3443b5a61abd8cfbf3112a","name":"Upstairs kitchen","relayState":"CLOSED","instantPowerW":-9.228373527526855,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":1.9281843900680542,"consumedEnergyWh":14129.44140625,"energyAccumUpdateTimeS":1661222964,"tabs":[25],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"dcea8872d6a1468dbc4d7cea16cd358e":{"id":"dcea8872d6a1468dbc4d7cea16cd358e","name":"Disposal","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":191.22520446777344,"consumedEnergyWh":300.55902099609375,"energyAccumUpdateTimeS":1661222964,"tabs":[27],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"3a6ee610e302492da680009185fe8980":{"id":"3a6ee610e302492da680009185fe8980","name":"Washing machine downstairs","relayState":"CLOSED","instantPowerW":0.0,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":0.5367056727409363,"consumedEnergyWh":155442.21875,"energyAccumUpdateTimeS":1661222964,"tabs":[29],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false},"dff42809566643079ade620c47767746":{"id":"dff42809566643079ade620c47767746","name":"Upstairs kitchen","relayState":"CLOSED","instantPowerW":-6.206461429595947,"instantPowerUpdateTimeS":1661223412,"producedEnergyWh":4.2532599763944745e-05,"consumedEnergyWh":14282.4853515625,"energyAccumUpdateTimeS":1661222964,"tabs":[31],"priority":"MUST_HAVE","is_user_controllable":true,"is_sheddable":false,"is_never_backup":false}}}`

**Comment by tylas13** [comment]
Sorry, that didn't format at all - and can't remember how to format it.   Must be getting late.

**Comment by tylas13** [comment]
Have you had a chance to look into it or getting the same errors?  I have left it run for the past week straight and it will update at random times, maybe 3-6 times per day.  This is the weird part for me, I can understand a crashing failure but not an intermittent grab and then hours without a pull.

I have tried to poke at the 0.0.4 version but can’t find any simple syntax issues, although I am not a coder by trade. 

Also got a new error type below.

`Logger: homeassistant.components.select
Source: custom_components/span_panel/select.py:57 
Integration: Select (documentation, issues) 
First occurred: September 5, 2022 at 12:44:26 AM (18 occurrences) 
Last logged: 6:56:15 AM

Error adding entities for domain select with platform span_panel
Error while setting up span_panel platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/span_panel/select.py", line 57, in current_option
    return PRIORITY_TO_HASS[priority]
KeyError: 'NON_ESSENTIAL'
`

**Comment by tylas13** [comment]
I have just uploaded Wez's fork, and so far so good.  Loaded without issue and no error's loading up, seems to be updating every 15 seconds as programmed. Thanks @wez!

**Comment by wez** [comment]
FWIW, my commit is a bit janky as it causes both "Non Essential" and "Not Essential" to show up as options for a given circuit.

**Comment by tylas13** [comment]
Oh, I see that now in the circuit options.  I am unconcerned personally at the moment since I don't have a battery backup system installed (yet), and the priorities only work with Span once that is established. 

Sounds like something that can be fixed with a Span version check, or we can have them stop renaming their key names :)
